### ISSUE TITLE
Finish off metaprogramming

### ISSUE THREAD

**Issue by hadley** [hadley/adv-r#1342]
* [x] Type in changes from print out
* [x] Suppress purrr conflicts in prerequisite blocks
* [x] Respond to GVW comments
* [x] Either remove number from intro sections or pull into separate chapter
* [x] Consider removing AST-walking case study. (Think about latex example implications)
* [x] Print complete part
* [x] Proof read complete part
* [x] Re-enter changes
